=== mouse0w0/peach/schema/model_definition.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Model Definition",
    "type": "object",
    "required": [
        "id",
        "models"
    ],
    "properties": {
        "id": {
            "type": "string"
        },
        "preview": {
            "type": "string"
        },
        "blockstates": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "textures": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "models": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "required": [
                    "template",
                    "name"
                ],
                "properties": {
                    "template": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "parent": {
                        "type": "string"
                    }
                },
                "additionalProperties": false
            }
        }
    },
    "additionalProperties": false
}

=== mouse0w0/peach/plugin/minecraft-1.12.2/model/cube_column.json
{
    "id": "minecraft:cube_column",
    "preview": "cube_column.json",
    "blockstates": [
        "normal", "directional", "horizontal", "pillar", "dirt"
    ],
    "textures": [
        "end", "side"
    ],
    "models": {
        "block": {
            "name": "block/${id}",
            "template": "cube_column.json"
        }
    }
}

=== mouse0w0/peach/plugin/minecraft-1.12.2/model/cube.json
{
    "id": "minecraft:cube",
    "preview": "cube.json",
    "blockstates": [
        "normal", "directional", "horizontal", "dirt"
    ],
    "textures": [
        "top", "bottom", "north", "south", "west", "east"
    ],
    "models": {
        "block": {
            "name": "block/${id}",
            "template": "cube.json"
        }
    }
}

=== mouse0w0/peach/plugin/minecraft-1.12.2/model/pane.json
{
    "id": "minecraft:pane",
    "preview": "pane.json",
    "blockstates": [
        "pane"
    ],
    "textures": [
        "pane", "edge"
    ],
    "models": {
        "pane_post": {
            "name": "block/${id}_post",
            "template": "pane_post.json"
        },
        "pane_side": {
            "name": "block/${id}_side",
            "template": "pane_side.json"
        },
        "pane_side_alt": {
            "name": "block/${id}_side_alt",
            "template": "pane_side_alt.json"
        },
        "pane_noside": {
            "name": "block/${id}_noside",
            "template": "pane_noside.json"
        },
        "pane_noside_alt": {
            "name": "block/${id}_noside_alt",
            "template": "pane_noside_alt.json"
        }
    }
}

=== mouse0w0/peach/plugin/minecraft-1.12.2/model/stairs.json
{
    "id": "minecraft:stairs",
    "preview": "stairs.json",
    "blockstates": [
        "stairs"
    ],
    "textures": [
        "bottom", "top", "side"
    ],
    "models": {
        "stairs": {
            "name": "block/${id}",
            "template": "stairs.json"
        },
        "outer_stairs": {
            "name": "block/${id}_outer",
            "template": "outer_stairs.json"
        },
        "inner_stairs": {
            "name": "block/${id}_inner",
            "template": "inner_stairs.json"
        }
    }
}

=== mouse0w0/peach/plugin/minecraft-1.12.2/model/trapdoor.json
{
    "id": "minecraft:trapdoor",
    "preview": "trapdoor.json",
    "blockstates": [
        "trapdoor"
    ],
    "textures": [
        "texture"
    ],
    "models": {
        "trapdoor_bottom": {
            "name": "block/${id}_bottom",
            "template": "trapdoor_bottom.json"
        },
        "trapdoor_top": {
            "name": "block/${id}_top",
            "template": "trapdoor_top.json"
        },
        "trapdoor_open": {
            "name": "block/${id}_open",
            "template": "trapdoor_open.json"
        }
    }
}

=== mouse0w0/peach/plugin/minecraft-1.12.2/model/wall.json
{
    "id": "minecraft:wall",
    "preview": "wall.json",
    "blockstates": [
        "wall"
    ],
    "textures": [
        "texture"
    ],
    "models": {
        "wall_post": {
            "name": "block/${id}_post",
            "template": "wall_post.json"
        },
        "wall_side": {
            "name": "block/${id}_side",
            "template": "wall_side.json"
        },
        "wall_inventory": {
            "name": "block/${id}_inventory",
            "template": "wall_inventory.json"
        }
    }
}

=== mouse0w0/peach/plugin/minecraft-1.12.2/model/cube_bottom_top.json
{
    "id": "minecraft:cube_bottom_top",
    "preview": "cube_bottom_top.json",
    "blockstates": [
        "normal", "directional", "horizontal", "dirt"
    ],
    "textures": [
        "bottom", "top", "side"
    ],
    "models": {
        "block": {
            "name": "block/${id}",
            "template": "cube_bottom_top.json"
        }
    }
}

=== mouse0w0/peach/plugin/minecraft-1.12.2/model/stone.json
{
    "id": "minecraft:stone",
    "preview": "cube.json",
    "blockstates": [
        "stone"
    ],
    "textures": [
        "top", "bottom", "north", "south", "west", "east"
    ],
    "models": {
        "block": {
            "name": "block/${id}",
            "template": "cube.json"
        },
        "block_mirrored": {
            "name": "block/${id}_mirrored",
            "template": "cube_mirrored.json"
        }
    }
}
