=== mouse0w0/peach/schema/model_definition.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Model Definition",
    "type": "object",
    "required": [
        "id",
        "models"
    ],
    "properties": {
        "id": {
            "type": "string"
        },
        "preview": {
            "type": "string"
        },
        "blockstates": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "textures": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "models": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "required": [
                    "template",
                    "name"
                ],
                "properties": {
                    "template": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "parent": {
                        "type": "string"
                    }
                },
                "additionalProperties": false
            }
        }
    },
    "additionalProperties": false
}

=== mouse0w0/peach/plugin/minecraft-1.12.2/model/fence_gate.json
{
    "id": "minecraft:fence_gate",
    "preview": "fence_gate.json",
    "blockstates": [
        "fence_gate"
    ],
    "textures": [
        "texture"
    ],
    "models": {
        "fence_gate_closed": {
            "name": "block/${id}_closed",
            "template": "fence_gate_closed.json"
        },
        "fence_gate_open": {
            "name": "block/${id}_open",
            "template": "fence_gate_open.json"
        },
        "wall_gate_closed": {
            "name": "block/${id}_wall_closed",
            "template": "wall_gate_closed.json"
        },
        "wall_gate_open": {
            "name": "block/${id}_wall_open",
            "template": "wall_gate_open.json"
        }
    }
}

=== mouse0w0/peach/plugin/minecraft-1.12.2/model/fence.json
{
    "id": "minecraft:fence",
    "preview": "fence.json",
    "blockstates": [
        "fence"
    ],
    "textures": [
        "texture"
    ],
    "models": {
        "fence_post": {
            "name": "block/${id}_post",
            "template": "fence_post.json"
        },
        "fence_side": {
            "name": "block/${id}_side",
            "template": "fence_side.json"
        }
    }
}

=== mouse0w0/peach/plugin/minecraft-1.12.2/model/slab.json
{
    "id": "minecraft:slab",
    "preview": "slab.json",
    "blockstates": [
        "slab"
    ],
    "textures": [
        "bottom", "top", "side"
    ],
    "models": {
        "slab_bottom": {
            "name": "block/${id}_bottom",
            "template": "slab_bottom.json"
        },
        "slab_top": {
            "name": "block/${id}_top",
            "template": "slab_top.json"
        },
        "slab_double": {
            "name": "block/${id}_double",
            "template": "cube_bottom_top.json"
        }
    }
}
